/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGraphiques;


import static com.usthb.modeles.ClientFacebook.seConnecter;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ITEC
 */
public class ConnexionFen extends javax.swing.JFrame {

    /**
     * Creates new form ConnexionFen
     */
    public ConnexionFen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        msgErreur2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        seConnecter = new javax.swing.JLabel();
        passwordCnx = new javax.swing.JPasswordField();
        usernameCnx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inscription = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setTitle("Little Facebook");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_32px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 30, 40));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msgErreur2.setBackground(new java.awt.Color(255, 255, 255));
        msgErreur2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        msgErreur2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel5.add(msgErreur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 240, 20));

        jSeparator2.setBackground(new java.awt.Color(196, 153, 136));
        jSeparator2.setForeground(new java.awt.Color(196, 153, 136));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 10));

        jPanel3.setBackground(new java.awt.Color(124, 164, 174,100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seConnecter.setBackground(new java.awt.Color(148, 156, 158));
        seConnecter.setFont(new java.awt.Font("Century Gothic", 0, 23)); // NOI18N
        seConnecter.setForeground(new java.awt.Color(240, 240, 240));
        seConnecter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seConnecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Login_Rounded_50px_2.png"))); // NOI18N
        seConnecter.setText("CONNEXION   ");
        seConnecter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seConnecter.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        seConnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seConnecterMouseClicked(evt);
            }
        });
        jPanel3.add(seConnecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 60));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 260, 60));

        passwordCnx.setBackground(new java.awt.Color(2, 77, 108));
        passwordCnx.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        passwordCnx.setForeground(new java.awt.Color(252, 252, 252));
        passwordCnx.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOT DE PASSE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        passwordCnx.setOpaque(false);
        passwordCnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordCnxActionPerformed(evt);
            }
        });
        jPanel5.add(passwordCnx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, 60));

        usernameCnx.setBackground(new java.awt.Color(51, 51, 51));
        usernameCnx.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        usernameCnx.setForeground(new java.awt.Color(255, 255, 255));
        usernameCnx.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOM D'UTILISATEUR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        usernameCnx.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameCnx.setOpaque(false);
        jPanel5.add(usernameCnx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 260, 60));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(196, 153, 136));
        jLabel5.setText("Connectez-vous maintenant !");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 210, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 310, 340));

        jLabel4.setBackground(new java.awt.Color(252, 252, 252));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(121, 118, 113));
        jLabel4.setText("Bienvenue sur LittleFacebook !");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 270, 30));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vous n'avez pas de compte? Inscrivez-vous ici!");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 280, 20));

        inscription.setBackground(new java.awt.Color(124, 164, 174));
        inscription.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        inscription.setForeground(new java.awt.Color(255, 255, 0));
        inscription.setText("S'inscrire");
        inscription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inscription.setOpaque(true);
        inscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inscriptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inscriptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inscriptionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inscriptionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                inscriptionMouseReleased(evt);
            }
        });
        jPanel2.add(inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 40));

        jLabel1.setBackground(new java.awt.Color(251, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 480));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 480));

        setSize(new java.awt.Dimension(361, 482));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seConnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seConnecterMouseClicked
   String username= usernameCnx.getText(),
               password= new String(passwordCnx.getPassword());
        
        try {
            switch(seConnecter(username,password)){
                case 0:
                    new MurFen().setVisible(true);
                    this.dispose();
                    break;
                case 1:
                    msgErreur2.setText("Username inexistant");
                    break;
                case 2:
                    msgErreur2.setText("Mot de passe erroné");
                    break;
                case 3:
                    msgErreur2.setText("Problème connexion");
                    break;
                    
            }
        } catch (IOException | ClassNotFoundException | InterruptedException ex) {
            Logger.getLogger(ConnexionFen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_seConnecterMouseClicked

    private void inscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscriptionMouseClicked
        this.dispose();
        InscriptionFen fen= new InscriptionFen();
        fen.setVisible(true);
    }//GEN-LAST:event_inscriptionMouseClicked

    private void passwordCnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordCnxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordCnxActionPerformed
                                    
    private void inscriptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscriptionMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inscriptionMousePressed

    private void inscriptionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscriptionMouseReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_inscriptionMouseReleased

    private void inscriptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscriptionMouseEntered
        // TODO add your handling code here:
        inscription.setForeground(Color.RED);
    }//GEN-LAST:event_inscriptionMouseEntered

    private void inscriptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscriptionMouseExited
        // TODO add your handling code here:
        inscription.setForeground(new Color(51,153,255));
    }//GEN-LAST:event_inscriptionMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     *//*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnexionFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnexionFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnexionFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnexionFen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel inscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel msgErreur2;
    private javax.swing.JPasswordField passwordCnx;
    private javax.swing.JLabel seConnecter;
    private javax.swing.JTextField usernameCnx;
    // End of variables declaration//GEN-END:variables
}
