
package interfacesGraphiques;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import static java.lang.System.in;
import static java.lang.System.out;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class InterfaceServeur extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceServeur
     */
    public InterfaceServeur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        bouton = new javax.swing.JButton();
        etat = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ferme(evt);
            }
        });

        bouton.setText("Eteindre");
        bouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonMouseClicked(evt);
            }
        });
        bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonActionPerformed(evt);
            }
        });

        etat.setText("Serveur allumé");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bouton)
                    .addComponent(etat, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(etat)
                .addGap(79, 79, 79)
                .addComponent(bouton)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonMouseClicked
        
    }//GEN-LAST:event_boutonMouseClicked

    private void boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonActionPerformed
        try {
        if(bouton.getText().startsWith("E")){
           
                eteindreServeur();
                bouton.setText("Allumer");
        }
        else{
            allumerServeur();
            bouton.setText("Eteindre");
        }
        } catch (IOException ex) {
                Logger.getLogger(InterfaceServeur.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_boutonActionPerformed

    private void ferme(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ferme
        try {
            eteindreServeur();
        } catch (IOException ex) {
            Logger.getLogger(InterfaceServeur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ferme

        public static void allumerServeur() throws UnknownHostException, IOException { //commentaire de user
            
             Socket socket = null;
             ObjectOutputStream out=null;
             ObjectInputStream in=null;
             try{
             socket = new Socket(InetAddress.getLocalHost(),2018);
             out=new ObjectOutputStream(socket.getOutputStream());
             in=new ObjectInputStream(socket.getInputStream());
             
             out.writeByte(0);
             out.flush();
             etat.setText("Serveur allumé");
             
             }finally{
             in.close();
             out.close();
             socket.close();
             }
             
             
        }
        
            public static void eteindreServeur() throws UnknownHostException, IOException { //commentaire de user
            
             Socket socket = null;
             ObjectOutputStream out=null;
             ObjectInputStream in=null;
             try{
             socket = new Socket(InetAddress.getLocalHost(),2018);
             out=new ObjectOutputStream(socket.getOutputStream());
             in=new ObjectInputStream(socket.getInputStream());
             
             out.writeByte(39);
             out.flush();
             etat.setText("Serveur éteint");
             
             }finally{
             in.close();
             out.close();
             socket.close();
             }
             
             
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton;
    private static javax.swing.JLabel etat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
